export type Lang = "es" | "en" | "de" | "fr";
export type Category =
  | "starters"
  | "main"
  | "grill"
  | "dessert"
  | "drinks-soft"
  | "drinks-beer"
  | "drinks-water"
  | "drinks-coffee"
  | "drinks-liquor"
  | "drinks-wine";

export type Dish = {
  id: string;
  category: Category;
  name: string;
  price?: number | null;
  priceShot?: number | null;
  priceGlass?: number | null;
  priceHalf?: number | null;
  priceWhole?: number | null;
  descriptions: Record<Lang, string>;
  i18nNames?: Partial<Record<Lang, string>>;
  image: string;
};

export const CAT_COLORS: Record<Category, string> = {
  starters: "#14b8a6",
  main: "#6366f1",
  grill: "#ef4444",
  dessert: "#ec4899",
  "drinks-soft": "#0ea5e9",
  "drinks-beer": "#f59e0b",
  "drinks-water": "#22c55e",
  "drinks-coffee": "#a16207",
  "drinks-liquor": "#7c3aed",
  "drinks-wine": "#be123c",
};

export const IMG: Record<Category, string> = {
  starters:
    "https://images.unsplash.com/p1111hoto-1551183053-bf91a1d81141?q=80&w=1200&auto=format&fit=crop2",
  main:
    "https://images.unsplash.com/pho1111to-1625944525567-c0f7c07e3992?q=80&w=1200&auto=format&fit=crop",
  grill:
    "https://images.unsplash.com/photo-1604908812837-0b6f64b2c329?q=80&w=1200&auto=format&fit=crop",
  dessert:
    "https://images.unsplash.com/photo-1541781286675-09d5f62b52dc?q=80&w=1200&auto=format&fit=crop",
  "drinks-soft":
    "https://images.unsplash.com/photo-1548839140-29a749e1cf4d?q=80&w=1200&auto=format&fit=crop",
  "drinks-beer":
    "https://images.unsplash.com/photo-1516455590571-18256e5bb9ff?q=80&w=1200&auto=format&fit=crop",
  "drinks-water":
    "https://images.unsplash.com/photo-1516275462205-1c59a3702f44?q=80&w=1200&auto=format&fit=crop",
  "drinks-coffee":
    "https://images.unsplash.com/photo-1503481766315-7a586b20f66b?q=80&w=1200&auto=format&fit=crop",
  "drinks-liquor":
    "https://images.unsplash.com/photo-1541976076758-347942db1978?q=80&w=1200&auto=format&fit=crop",
  "drinks-wine":
    "https://images.unsplash.com/photo-1524594154908-edd2f08f9635?q=80&w=1200&auto=format&fit=crop",
};

export const slug = (s: string) =>
  s
    .toLowerCase()
    .normalize("NFD")
    .replace(/\p{Diacritic}/gu, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");

export const DISHES: Dish[] = [
  {
    id: slug("Empanadas"),
    category: "starters",
    name: "Empanadas (unidad)",
    i18nNames: {
      es: "Empanadas (unidad)",
      en: "Empanadas (per unit)",
      de: "Empanadas (Stück)",
      fr: "Empanadas (à l’unité)",
    },
    price: 2.0,
    descriptions: {
      es: "Masa de maíz frita con relleno casero y salsa aji. Ingredientes: Harina de maiz.Relleno:carne desmechada lapa y Guiso: puerro,tomate,ajo,tomillo,orégano comino, colorante.Aji:puerro,tomate,cayena,pimiento,cilantro,sal ,limon, aceite.",
      en: "Fried corn dough with homemade filling & aji sauce. Ingredients: corn flour. Filling: shredded beef. Stew: leek, tomato, garlic, thyme, oregano, cumin, food coloring. Aji: leek, tomato, cayenne, pepper, coriander, salt, lemon, oil.",
      de: "Frittierter Maisteig mit hausgemachter Füllung & Aji-Sauce. Zutaten: Maismehl. Füllung: zerrissenes Rindfleisch. Eintopf: Lauch, Tomate, Knoblauch, Thymian, Oregano, Kreuzkümmel, Lebensmittelfarbe. Aji: Lauch, Tomate, Cayennepfeffer, Paprika, Koriander, Salz, Zitrone, Öl.",
      fr: "Pâte de maïs frite avec garniture maison & sauce aji. Ingrédients : farine de maïs. Garniture : bœuf effiloché. Ragoût : poireau, tomate, ail, thym, origan, cumin, colorant alimentaire. Aji : poireau, tomate, piment de Cayenne, poivron, coriandre, sel, citron, huile.",
    },
    image: "img/platos/empanada.jpg",
  },
  {
    id: slug("Papa rellena"),
    category: "starters",
    name: "Papa rellena",
    i18nNames: {
      es: "Papa rellena",
      en: "Stuffed potato",
      de: "Gefüllte Kartoffel",
      fr: "Pomme de terre farcie",
    },
    price: 4.0,
    descriptions: {
      es: "Bola de papa rellena y dorada. Ingredientes: Papa guisada, arroz, aceite, huevo duro, carne desmechada, guiso: puerro, tomate, ajo, tomillo, orégano, comino, colorante, harina de trigo.",
      en: "Golden stuffed potato ball. Ingredients: stewed potato, rice, oil, hard-boiled egg, shredded meat, stew: leek, tomato, garlic, thyme, oregano, cumin, coloring, wheat flour.",
      de: "Goldbraune, gefüllte Kartoffelkugel. Zutaten: geschmorte Kartoffel, Reis, Öl, hartgekochtes Ei, zerrissenes Fleisch, Eintopf: Lauch, Tomate, Knoblauch, Thymian, Oregano, Kreuzkümmel, Farbstoff, Weizenmehl.",
      fr: "Boule de pomme de terre farcie, dorée. Ingrédients : pomme de terre mijotée, riz, huile, œuf dur, viande effilochée, ragoût : poireau, tomate, ail, thym, origan, cumin, colorant, farine de blé.",
    },
    image: IMG["starters"],
  },
  {
    id: slug("Arepa con chorizo antioqueño"),
    category: "starters",
    name: "Arepa con chorizo antioqueño",
    i18nNames: {
      es: "Arepa con chorizo antioqueño",
      en: "Arepa with Antioquian chorizo",
      de: "Arepa mit Antioquian Wurst",
      fr: "Arepa au chorizo antioqueno",
    },
    price: 7.0,
    descriptions: {
      es: "Arepa de maíz con chorizo antioqueño. Ingredientes: Harina de maíz, chorizo antioqueño, sal, limón.",
      en: "Corn arepa with Antioquian chorizo. Ingredients: corn flour, Antioquian chorizo, salt, lemon.",
      de: "Mais-Arepa mit Antioquian Wurst. Zutaten: Maismehl, Antioquian Wurst, Salz, Zitrone.",
      fr: "Arepa de maïs au chorizo antioqueño. Ingrédients : farine de maïs, chorizo antioqueño, sel, citron.",
    },
    image: IMG["starters"],
  },
  {
    id: slug("Arepa con chicharron"),
    category: "starters",
    name: "Arepa con chicharrón",
    i18nNames: {
      es: "Arepa con chicharrón",
      en: "Arepa with pork rind",
      de: "Arepa mit Schweineschwarte",
      fr: "Arepa au chicharrón",
    },
    price: 7.0,
    descriptions: {
      es: "Arepa de maíz con chicharrón crujiente. Ingredientes: Harina de maíz.Chicharrón:sal,limón .",
      en: "Corn arepa with crispy pork rind. Ingredients: corn flour, pork rind, salt, lemon.",
      de: "Mais-Arepa mit knuspriger Schweineschwarte. Zutaten: Maismehl, Schweineschwarte, Salz, Zitrone.",
      fr: "Arepa de maïs au chicharrón croustillant. Ingrédients : farine de maïs, couenne de porc, sel, citron.",
    },
    image: "img/platos/arepa-chicharron.jpg",
  },
  {
    id: slug("Patacon con hogao"),
    category: "starters",
    name: "Patacón con hogao",
    i18nNames: {
      es: "Patacón con hogao",
      en: "Patacón with hogao",
      de: "Patacón mit Hogao",
      fr: "Patacón au hogao",
    },
    price: 7.0,
    descriptions: {
      es: "Plátano verde frito con salsa criolla. Ingredientes: Platano verde, Hogado:puerro,tomate,ajo,tomillo,orégano ,comino,colorante.",
      en: "Fried green plantain with Creole sauce. Ingredients: green plantain, Hogao: leek, tomato, garlic, thyme, oregano, cumin, food coloring.",
      de: "Frittierte Kochbanane mit kreolischer Sauce. Zutaten: Kochbanane, Lauch, Tomate, Knoblauch, Thymian, Oregano, Kreuzkümmel, Farbstoff.",
      fr: "Banane plantain frite avec sauce créole. Ingrédients : plantain vert, poireau, tomate, ail, thym, origan, cumin, colorant.",
    },
    image: "img/platos/patacon-hogao.jpg",
  },
  {
    id: slug("Patacon con queso"),
    category: "starters",
    name: "Patacón con queso",
    i18nNames: {
      es: "Patacón con queso",
      en: "Patacón with cheese",
      de: "Patacón mit Käse",
      fr: "Patacón au fromage",
    },
    price: 7.0,
    descriptions: {
      es: "Patacón crujiente con queso fresco rallado. Ingredientes:Plátano verde, queso fresco rallado.",
      en: "Crispy patacón with grated fresh cheese. Ingredients: green plantain, grated fresh cheese.",
      de: "Knuspriger Patacón mit geriebenem Frischkäse. Zutaten: grüne Kochbanane, geriebener Frischkäse.",
      fr: "Patacón croustillant au fromage frais râpé. Ingrédients : plantain vert, fromage frais râpé.",
    },
    image: IMG["starters"],
  },
  {
    id: slug("Queso a la plancha"),
    category: "starters",
    name: "Queso a la plancha",
    i18nNames: {
      es: "Queso a la plancha",
      en: "Grill cheese",
      de: "Gegrillter Käse",
      fr: "Fromage grillé",
    },
    price: 9.50,
    descriptions: {
      es: "Queso dorado a la plancha. Ingredientes:Queso ahumado, Mojo rojo: pimiento,comino,pimenton sal aceite vinagre.Mojo verde: cilantro,perejil,ajo,comino,sal aceite, vinagre.Mermelada de arandanos.",
      en: "Seared cheese, golden and melty. Ingredients: smoked cheese, Red mojo: pepper, cumin, paprika, salt, oil, vinegar. Green mojo: coriander, parsley, garlic, cumin, salt, oil, vinegar. Cranberry jam.",
      de: "Auf der Platte gebräunter Käse. Zutaten: geräucherter Käse, Rotes Mojo: Paprika, Kreuzkümmel, Paprika, Salz, Öl, Essig. Grünes Mojo: Koriander, Petersilie, Knoblauch, Kreuzkümmel, Salz, Öl, Essig. Preiselbeermarmelade.",
      fr: "Fromage saisi et fondant. Ingrédients : fromage fumé, Mojo rouge : poivron, cumin, paprika, sel, huile, vinaigre. Mojo vert : coriandre, persil, ail, cumin, sel, huile, vinaigre. Confiture de canneberges.",
    },
    image: IMG["starters"],
  },
  {
    id: slug("Gambas al ajillo"),
    category: "starters",
    name: "Gambas al ajillo",
    i18nNames: {
      es: "Gambas al ajillo",
      en: "Garlic prawns",
      de: "Garnelen in Knoblauch",
      fr: "Crevettes à l’ail",
    },
    price: 9.0,
    descriptions: {
      es: "Salteados con ajo y aceite de oliva. Ingredientes: Gambas, ajo, aceite oliva, perejil, sal, cayena, brandy.",
      en: "Sautéed with garlic and olive oil. Ingredients: prawns, garlic, olive oil, parsley, salt, cayenne, brandy.",
      de: "Mit Knoblauch in Olivenöl sautiert. Zutaten: Garnelen, Knoblauch, Olivenöl, Petersilie, Salz, Cayennepfeffer, Brandy.",
      fr: "Sautés à l’ail et huile d’olive. Ingrédients : crevettes, ail, huile d’olive, persil, sel, piment de Cayenne, brandy.",
    },
    image: IMG["starters"],
  },
  {
    id: slug("Huevos estrellados"),
    category: "starters",
    name: "Huevos estrellados",
    i18nNames: {
      es: "Huevos estrellados",
      en: "Scrambled eggs",
      de: "Rühreier",
      fr: "Œufs brouillés",
    },
    price: 6.50,
    descriptions: {
      es: "Cremosos al estilo casero. Ingredientes:Huevos fritos, papas naturales fritas, pimenton  chotizo, perejil.",
      en: "Creamy, home-style. Ingredients: fried eggs, natural fried potatoes, paprika, chorizo, parsley.",
      de: "Cremig & hausgemacht. Zutaten: Spiegeleier, natürliche Bratkartoffeln, Paprika, Chorizo, Petersilie.",
      fr: "Crémeux, façon maison. Ingrédients : œufs au plat, pommes de terre sautées nature, paprika, chorizo, persil.",
    },
    image: "img/platos/huevos.jpg",
  },
  {
    id: slug("Escaldon"),
    category: "starters",
    name: "Escaldón",
    i18nNames: {
      es: "Escaldón",
      en: "Escaldón",
      de: "Escaldón",
      fr: "Escaldón",
    },
    price: 6.0,
    descriptions: {
      es: "Gofio ligado con caldo. Ingredientes:Gofio con Caldo: sobrebarriga, sal, ajo, comino, oregano, tomillo .Carne desmechada de sobrebarriga,cebolla blanca,Mojo rojo: pimiento,comino,pimenton sal aceite vinagre.Mojo verde: cilantro,perejil,ajo,comino,sal aceite, vinagre.Queso ahumado pasteurizado.",
      en: "Gofio worked with broth. Ingredients: Gofio with Broth: flank steak, salt, garlic, cumin, oregano, thyme. Shredded flank steak, white onion. Red mojo: pepper, cumin, paprika, salt, oil, vinegar. Green mojo: coriander, parsley, garlic, cumin, salt, oil, vinegar. Smoked pasteurized cheese.",
      de: "Gofio mit Brühe verarbeitet. Zutaten: Gofio mit Brühe: Flankensteak, Salz, Knoblauch, Kreuzkümmel, Oregano, Thymian. Zerrissenes Flankensteak, weiße Zwiebel. Rotes Mojo: Paprika, Kreuzkümmel, Paprika, Salz, Öl, Essig. Grünes Mojo: Koriander, Petersilie, Knoblauch, Kreuzkümmel, Salz, Öl, Essig. Geräucherter pasteurisierter Käse.",
      fr: "Gofio travaillé avec du bouillon. Ingrédients : Gofio avec bouillon : flank steak, sel, ail, cumin, origan, thym. Flank steak effiloché, oignon blanc. Mojo rouge : poivron, cumin, paprika, sel, huile, vinaigre. Mojo vert : coriandre, persil, ail, cumin, sel, huile, vinaigre. Fromage pasteurisé fumé.",
    },
    image: "",
  },
  {
    id: slug("Papas arrugadas con mojo"),
    category: "starters",
    name: "Papas arrugadas con mojo",
    i18nNames: {
      es: "Papas arrugadas con mojo",
      en: "Wrinkled potatoes with mojo",
      de: "Runzelkartoffeln mit Mojo",
      fr: "Pommes de terre « arrugadas » au mojo",
    },
    price: 4.50,
    descriptions: {
      es: "papas canarias con mojo rojo o verde. Ingredientes:Papa arrugada en agua,sal limon. Mojo rojo: pimiento,comino,pimenton sal aceite vinagre.Mojo verde: cilantro,perejil,ajo,comino,sal aceite, vinagre.",
      en: "Canarian potatoes with red or green mojo. Ingredients: wrinkled potato in water, salt, lemon. Red mojo: pepper, cumin, paprika, salt, oil, vinegar. Green mojo: coriander, parsley, garlic, cumin, salt, oil, vinegar.",
      de: "Kanarische Kartoffeln mit rotem oder grünem Mojo. Zutaten: runzelige Kartoffel in Wasser, Salz, Zitrone. Rotes Mojo: Paprika, Kreuzkümmel, Paprika, Salz, Öl, Essig. Grünes Mojo: Koriander, Petersilie, Knoblauch, Kreuzkümmel, Salz, Öl, Essig.",
      fr: "Pommes de terre des Canaries au mojo rouge ou vert. Ingrédients : pomme de terre ridée dans l’eau, sel, citron. Mojo rouge : poivron, cumin, paprika, sel, huile, vinaigre. Mojo vert : coriandre, persil, ail, cumin, sel, huile, vinaigre.",
    },
    image: "img/platos/papas-arrugadas.jpg",
  },
  {
    id: slug("Ensalada mixta"),
    category: "starters",
    name: "Ensalada mixta",
    i18nNames: {
      es: "Ensalada mixta",
      en: "Mixed salad",
      de: "Gemischter Salat",
      fr: "Salade mixte",
    },
    price: 6.0,
    descriptions: {
      es: "Verdes, tomate y cebolla. Ingredientes: Lechuga, tomate, cebolla blanca, maiz, zanahoria rallada, aguacate, limón.",
      en: "Greens, tomato & onion. Ingredients: lettuce, tomato, white onion, corn, grated carrot, avocado, lemon.",
      de: "Blattsalat, Tomate, Zwiebel. Zutaten: Salat, Tomate, weiße Zwiebel, Mais, geriebene Karotte, Avocado, Zitrone.",
      fr: "Salade, tomate, oignon. Ingrédients : salade, tomate, oignon blanc, maïs, carotte râpée, avocat, citron.",
    },
    image: "img/platos/ensalada-mixta.jpg",
  },
  {
    id: slug("Ensalada Sazon de mi Tierra"),
    category: "starters",
    name: "Ensalada Sazón de mi Tierra",
    i18nNames: {
      es: "Ensalada Sazón de mi Tierra",
      en: "Sazón from my Land salad",
      de: "Salat « Sazón de mi Tierra »",
      fr: "Salade « Sazón de mi Tierra »",
    },
    price: 9.50,
    descriptions: {
      es: "Ensalada de la casa. Ingredientes:Col blanca, tomate,zanahoria rallada, huevo duro,aguacate, maiz,Aderezo:cebolla blanca, pimiento  mahonesa.Chicharron:sal, limón.",
      en: "House salad. Ingredients: white cabbage, tomato, grated carrot, hard-boiled egg, avocado, corn, Dressing: white onion, pepper, mayonnaise. Chicharrón: salt, lemon.",
      de: "Haussalat. Zutaten: Weißkohl, Tomate, geriebene Karotte, hartgekochtes Ei, Avocado, Mais, Dressing: weiße Zwiebel, Paprika, Mayonnaise. Chicharrón: Salz, Zitrone.",
      fr: "Salade maison. Ingrédients : chou blanc, tomate, carotte râpée, œuf dur, avocat, maïs, Vinaigrette : oignon blanc, poivron, mayonnaise. Chicharrón : sel, citron.",
    },
    image: "img/platos/ensalada-sazon.jpg",
  },

  /* ---------- MAIN DISHES (incluye sopas del PDF) ---------- */
  {
    id: slug("Bandeja paisa"),
    category: "main",
    name: "Bandeja paisa",
    i18nNames: {
      es: "Bandeja paisa",
      en: "Bandeja paisa",
      de: "Bandeja paisa",
      fr: "Bandeja paisa",
    },
    price: 16.5,
    descriptions: {
      es: "Clásico colombiano. Ingredientes: Frijoles:judia roja,sal,comino,orégano, tomillo,color alimentario ,cuero de cerdo.Carne molida:carne de ternera y cerdo,sal,ajo,colorante alimentario y comino.Arroz blanco:arroz sal y aceite.Arepa:harina de maiz,sal.Huevo frito.Chorizo antioqueño.Platano mauro frito.Aguacate.Chicharron:panceta ,sal y limón.",
      en: "Colombian classic. Ingredients: Beans: red beans, salt, cumin, oregano, thyme, food coloring, pork rind. Ground meat: beef and pork, salt, garlic, food coloring and cumin. White rice: rice, salt and oil. Arepa: corn flour, salt. Fried egg. Antioquian chorizo. Fried ripe plantain. Avocado. Pork rind: pork belly, salt and lemon.",
      de: "Kolumbianischer Klassiker. Zutaten: Bohnen: rote Bohnen, Salz, Kreuzkümmel, Oregano, Thymian, Lebensmittelfarbe, Schweineschwarte. Hackfleisch: Rind- und Schweinefleisch, Salz, Knoblauch, Lebensmittelfarbe und Kreuzkümmel. Weißer Reis: Reis, Salz und Öl. Arepa: Maismehl, Salz. Spiegelei. Antioquian Wurst. Gebratene reife Kochbanane. Avocado. Schweineschwarte: Schweinebauch, Salz und Zitrone.",
      fr: "Classique colombien. Ingrédients : Haricots : haricots rouges, sel, cumin, origan, thym, colorant alimentaire, couenne de porc. Viande hachée : bœuf et porc, sel, ail, colorant alimentaire et cumin. Riz blanc : riz, sel et huile. Arepa : farine de maïs, sel. Œuf au plat. Chorizo antioqueno. Banane plantain mûre frite. Avocat. Couenne de porc : poitrine de porc, sel et citron.",
    },
    image: "img/platos/bandeja-paisa.jpg",
  },
  {
    id: slug("Chuleta valluna"),
    category: "main",
    name: "Chuleta valluna",
    i18nNames: {
      es: "Chuleta valluna",
      en: "Valluna chop",
      de: "Valluna-Kotelett",
      fr: "Côte valluna",
    },
    price: 15.50,
    descriptions: {
      es: "Empanada y crujiente.Con punta de ensalada y papas fritas. Ingredientes: Bistec de cerdo, pan rallado,harina de trigo, huevo, sal,comino.",
      en: "Breaded & crispy. Served with side salad & fries. Ingredients: pork chop, bread crumbs, wheat flour, egg, salt, cumin.",
      de: "Paniert & knusprig. Mit Beilagensalat & Pommes frites. Zutaten: Schweinekotelett, Semmelbrösel, Weizenmehl, Ei, Salz, Kreuzkümmel.",
      fr: "Panée & croustillante. Servie avec salade garnie & frites. Ingrédients : côtelette de porc, chapelure, farine de blé, œuf, sel, cumin.",
    },
    image: "img/platos/valluna.jpg",
  },
  {
    id: slug("Sobrebarriga asada"),
    category: "main",
    name: "Sobrebarriga asada",
    i18nNames: {
      es: "Sobrebarriga asada",
      en: "Roasted flank steak",
      de: "Gebratener Flankensteak",
      fr: "Flank steak rôti",
    },
    price: 16.0,
    descriptions: {
      es: "Jugosa y dorada. Ingredientes:Sobrebarriga:sal,ajo,comino,oregano,tomillo.Papa natural.Punta de ensalada:lechuga,cebolla blanca,maiz,zanahoria rallada, tomate, limón. ",
      en: "Juicy and golden. Ingredients: flank steak: salt, garlic, cumin, oregano, thyme. Natural potato. Salad garnish: lettuce, white onion, corn, grated carrot, tomato, lemon.",
      de: "Saftig & goldbraun. Zutaten: Flankensteak: Salz, Knoblauch, Kreuzkümmel, Oregano, Thymian. Naturkartoffel. Salatgarnitur: Salat, weiße Zwiebel, Mais, geriebene Karotte, Tomate, Zitrone.",
      fr: "Juteuse & dorée. Ingrédients : flank steak : sel, ail, cumin, origan, thym. Pomme de terre nature. Garniture de salade : laitue, oignon blanc, maïs, carotte râpée, tomate, citron.",
    },
    image: IMG["main"],
  },
  {
    id: slug("Sobrebarriga en salsa"),
    category: "main",
    name: "Sobrebarriga en salsa",
    i18nNames: {
      es: "Sobrebarriga en salsa",
      en: "Flank steak in sauce",
      de: "Flankensteak in Sauce",
      fr: "Flank steak en sauce",
    },
    price: 17.30,
    descriptions: {
      es: "Guisada tierna. Ingredientes: Sobrebarriga:sal,ajo,comino,orégano,tomillo.Guiso: cebolla blanca, tomate, colorante alimentario, ajo,comino.Arroz blanco:arroz,sal,aceite.Papa guisada .Punta de ensalada:lechuga,cebolla blanca,maiz,zanahoria  rallada, tomate limón.",
      en: "Braised & tender. Ingredients: flank steak: salt, garlic, cumin, oregano, thyme. Stew: white onion, tomato, food coloring, garlic, cumin. White rice: rice, salt, oil. Stewed potato. Salad garnish: lettuce, white onion, corn, grated carrot, tomato, lemon.",
      de: "Geschmort & zart. Zutaten: Flankensteak: Salz, Knoblauch, Kreuzkümmel, Oregano, Thymian. Eintopf: weiße Zwiebel, Tomate, Lebensmittelfarbe, Knoblauch, Kreuzkümmel. Weißer Reis: Reis, Salz, Öl. Geschmorte Kartoffel. Salatgarnitur: Salat, weiße Zwiebel, Mais, geriebene Karotte, Tomate, Zitrone.",
      fr: "Braisée & fondante. Ingrédients : flank steak : sel, ail, cumin, origan, thym. Ragoût : oignon blanc, tomate, colorant alimentaire, ail, cumin. Riz blanc : riz, sel, huile. Pomme de terre mijotée. Garniture de salade : laitue, oignon blanc, maïs, carotte râpée, tomate, citron.",
    },
    image: IMG["main"],
  },
  {
    id: slug("Picada colombiana"),
    category: "main",
    name: "Picada colombiana",
    i18nNames: {
      es: "Picada colombiana",
      en: "Colombian platter",
      de: "Kolumbianische Platte",
      fr: "Assortiment colombien",
    },
    price: 30.0,
    descriptions: {
      es: "Para compartir. Ingredientes: Bofe.chunchulo, chorizo  antioqueño,pollo  chicharrones , patacones ,Arepa: harina de maíz, sal.",
      en: "To share. Ingredients: beef lung, chunchulo, Antioquian chorizo, chicken, pork rinds, patacones, arepa: corn flour, salt.",
      de: "Zum Teilen. Zutaten: Rinderlunge, Chunchulo, Antioquian Wurst, Huhn, Schweineschwarte, Patacones, Arepa: Maismehl, Salz.",
      fr: "À partager. Ingrédients : poumon de bœuf, chunchulo, chorizo antioqueno, poulet, couenne de porc, patacones, arepa : farine de maïs, sel.",
    },
    image: IMG["main"],
  },
  {
    id: slug("Carne fiestera"),
    category: "main",
    name: "Carne fiestera (adobada)",
    i18nNames: {
      es: "Carne fiestera (adobada)",
      en: "Party meat (marinated)",
      de: "Mariniertes Festfleisch",
      fr: "Viande « fiestera » marinée",
    },
    price: 9.0,
    descriptions: {
      es: "Tiras marinadas. Ingredientes: Tacos de cerdo,Adobo, ajo, comino, pimentón, aceite,tomillo,orégano ,vino.Papa fritas.Perejil.Limón. ",
      en: "Marinated strips. Ingredients: pork meat chunks, garlic, cumin, paprika, oil, thyme, oregano, wine. French fries. Parsley. Lemon.",
      de: "Marinierte Streifen. Zutaten: Schweinefleischstücke, Knoblauch, Kreuzkümmel, Paprika, Öl, Thymian, Oregano, Wein. Pommes frites. Petersilie. Zitrone.",
      fr: "Lanières marinées. Ingrédients : morceaux de viande de porc, ail, cumin, paprika, huile, thym, origan, vin. Frites. Persil. Citron.",
    },
    image: IMG["main"],
  },
  {
    id: slug("Costillas con papas y mazorca"),
    category: "main",
    name: "Costillas con papas y mazorca",
    i18nNames: {
      es: "Costillas con piña",
      en: "Ribs with potatoes & corn",
      de: "Rippen mit Kartoffeln & Mais",
      fr: "Côtes avec pommes de terre & maïs",
    },
    price: 10.5,
    descriptions: {
      es: "Guarnición campesina. Ingredientes: Tiras de costillas de cerdo saladas, papa, mazorca.Mojo verde: ajo,comino,sal,aceite,vinagre.",
      en: "Rustic garnish. Ingredients: salted pork rib strips, potato, corn. Green mojo: garlic, cumin, salt, oil, vinegar.",
      de: "Rustikale Beilage. Zutaten: gesalzene Schweinerippchenstreifen, Kartoffel, Mais. Grünes Mojo: Knoblauch, Kreuzkümmel, Salz, Öl, Essig.",
      fr: "Garniture rustique. Ingrédients : lanières de côtes de porc salées, pomme de terre, maïs. Mojo vert : ail, cumin, sel, huile, vinaigre.",
    },
    image: "img/platos/costilla-piña.jpg",
  },
  {
    id: slug("Carne de cabra"),
    category: "main",
    name: "Carne de cabra",
    i18nNames: {
      es: "Carne de cabra",
      en: "Goat meat stew",
      de: "Ziegeneintopf",
      fr: "Ragoût de chèvre",
    },
    price: 14.5,
    descriptions: {
      es: "Guiso tradicional. Ingredientes:Tacos de cabra, tomate, cebolla, pimiento,ajo, vino, laurel,tomillo,oregano,colorante alimentario.",
      en: "Traditional stew. Ingredients: goat meat chunks, tomato, onion, pepper, garlic, wine, bay leaf, thyme, oregano, food coloring.",
      de: "Traditioneller Eintopf. Zutaten: Ziegenfleischstücke, Tomate, Zwiebel, Paprika, Knoblauch, Wein, Lorbeer, Thymian, Oregano, Lebensmittelfarbe.",
      fr: "Ragoût traditionnel. Ingrédients : morceaux de viande de chèvre, tomate, oignon, poivron, ail, vin, feuille de laurier, thym, origan, colorant alimentaire.",
    },
    image: "img/platos/carne-cabra.jpg",
  },
  {
    id: slug("Garbanzas"),
    category: "main",
    name: "Garbanzas",
    i18nNames: {
      es: "Garbanzas",
      en: "Chickpeas stew",
      de: "Kichererbsen-Eintopf",
      fr: "Ragoût de pois chiches",
    },
    price: 8.0,
    descriptions: {
      es: "Estilo casero. Ingredientes:Garbanzas, tomate, cebolla, pimiento, costillas de cerdo,panceta, chorizo sarta,ajo,comino,laurel ,oregano,tomillo,colorante alimentario pimienta negra.",
      en: "Home-style. Ingredients: chickpeas, tomato, onion, pepper, pork ribs, pork belly, chorizo sausage, garlic, cumin, bay leaf, oregano, thyme, food coloring, black pepper.",
      de: "Hausgemacht. Zutaten: Kichererbsen, Tomate, Zwiebel, Paprika, Schweinerippchen, Schweinebauch, Chorizo, Knoblauch, Kreuzkümmel, Lorbeer, Oregano, Thymian, Lebensmittelfarbe, schwarzer Pfeffer.",
      fr: "Maison. Ingrédients : pois chiches, tomate, oignon, poivron, côtes de porc, poitrine de porc, chorizo, ail, cumin, laurier, origan, thym, colorant alimentaire, poivre noir.",
    },
    image: IMG["main"],
  },
  {
    id: slug("Potaje de lentejas"),
    category: "main",
    name: "Potaje de lentejas",
    i18nNames: {
      es: "Potaje de lentejas",
      en: "Lentil stew",
      de: "Linseneintopf",
      fr: "Ragoût de lentilles",
    },
    price: 6.50,
    descriptions: {
      es: "Clásico y nutritivo. Ingredientes: Lenteja, zanahoria, papa,calabaza,calabacin,cebolla,pimiento,ajo, laurel, comino,pimienta  negra,colorante alimentario,sal,costillade cerdo,panceta,chorizo  sarta.",
      en: "Classic & hearty. Ingredients: lentils, carrot, potato, pumpkin, zucchini, onion, pepper, garlic, bay leaf, cumin, black pepper, food coloring, salt, pork ribs, pork belly, chorizo sausage.",
      de: "Klassisch & herzhaft. Zutaten: Linsen, Karotte, Kartoffel, Kürbis, Zucchini, Zwiebel, Paprika, Knoblauch, Lorbeer, Kreuzkümmel, schwarzer Pfeffer, Lebensmittelfarbe, Salz, Schweinerippchen, Schweinebauch, Chorizo.",
      fr: "Classique & copieux. Ingrédients : lentilles, carotte, pomme de terre, potiron, courgette, oignon, poivron, ail, laurier, cumin, poivre noir, colorant alimentaire, sel, côtes de porc, poitrine de porc, chorizo.",
    },
    image: IMG["main"],
  },
  {
    id: slug("Potaje de berros"),
    category: "main",
    name: "Potaje de berros",
    i18nNames: {
      es: "Potaje de berros",
      en: "Watercress stew",
      de: "Brunnenkresse-Eintopf",
      fr: "Ragoût de cresson",
    },
    price: 6.50,
    descriptions: {
      es: "Vegetal y aromático. Ingredientes:Berros, papa, batata,calabaza, cebolla,tomate ajo,costilla de cerdo,panceta, chorizo ,sarta,comino,oregano,laurel,tomillo,aceite,judias,pimienta negra.",
      en: "Vegetable & aromatic. Ingredients: watercress, potato, sweet potato, pumpkin, onion, tomato, garlic, pork ribs, pork belly, chorizo sausage, cumin, oregano, bay leaf, thyme, oil, beans, black pepper.",
      de: "Gemüsig & aromatisch. Zutaten: Brunnenkresse, Kartoffel, Süßkartoffel, Kürbis, Zwiebel, Tomate, Knoblauch, Schweinerippchen, Schweinebauch, Chorizo, Kreuzkümmel, Oregano, Lorbeer, Thymian, Öl, Bohnen, schwarzer Pfeffer.",
      fr: "Végétal & aromatique. Ingrédients : cresson, pomme de terre, patate douce, potiron, oignon, tomate, ail, côtes de porc, poitrine de porc, chorizo, cumin, origan, laurier, thym, huile, haricots, poivre noir.",
    },
    image: IMG["main"],
  },
  // Sopas del PDF (Main Dishes)
  {
    id: slug("Sancocho de gallina"),
    category: "main",
    name: "Sancocho de gallina (domingos)",
    i18nNames: {
      es: "Sancocho de gallina (domingos)",
      en: "Hen sancocho (Sundays)",
      de: "Hühnersancocho (sonntags)",
      fr: "Sancocho de poule (dimanches)",
    },
    price: 17.0,
    descriptions: {
      es: "Plato tipico compuesto de un primer plato de caldo y un segundo con gallina en salsa y guarnición. Ingredientes:Sancocho:platano,yuca,papa,ajo,comino,sal,cilantro,gallina.Punta de ensalada:lechuga,cebolla blanca,maiz,tomate y limón. Arroz:arroz blanco,sal,aceite.Salsa o guiso:cebolla blanca,tomate,ajo,comino,colorante alimentario.",
      en: "Typical dish consisting of a first course of broth and a second with hen in sauce and garnish. Ingredients: Sancocho: plantain, cassava, potato, garlic, cumin, salt, coriander, hen. Salad garnish: lettuce, white onion, corn, tomato & lemon. Rice: white rice, salt, oil. Sauce or stew: white onion, tomato, garlic, cumin, food coloring.",
      de: "Typisches Gericht, das aus einem ersten Gang Brühe und einem zweiten mit Huhn in Sauce und Beilage besteht. Zutaten: Sancocho: Kochbanane, Maniok, Kartoffel, Knoblauch, Kreuzkümmel, Salz, Koriander, Huhn. Salatgarnitur: Salat, weiße Zwiebel, Mais, Tomate & Zitrone. Reis: weißer Reis, Salz, Öl. Sauce oder Eintopf: weiße Zwiebel, Tomate, Knoblauch, Kreuzkümmel, Lebensmittelfarbe.",
      fr: "Plat typique composé d'un premier plat de bouillon et d'un second avec de la poule en sauce et garniture. Ingrédients : sancocho : banane plantain, manioc, pomme de terre, ail, cumin, sel, coriandre, poule. Garniture de salade : laitue, oignon blanc, maïs, tomate & citron. Riz : riz blanc, sel, huile. Sauce ou ragoût : oignon blanc, tomate, ail, cumin, colorant alimentaire.",
    },
    image: "img/platos/sancocho-gallina.jpg",
  },
  {
    id: slug("Sancocho trifasico"),
    category: "main",
    name: "Sancocho trifásico (sábados)",
    i18nNames: {
      es: "Sancocho trifásico (sábados)",
      en: "Trifásico sancocho (Saturdays)",
      de: "Dreifacher Sancocho (samstags)",
      fr: "Sancocho « trifásico » (samedis)",
    },
    price: 19.90,
    descriptions: {
      es: "Plato tipico compuesto de un primer plato de caldo y un segundo con costilla de res,costilla de cerdo,gallina ,las tres carnes  en salsa y  guarnición. Ingredientes: Sancocho:platano,yuca,papa,ajo,comino,sal,cilantro,costilla de res,costilla de cerdo,gallina.Punta de ensalada:lechuga,cebolla blanca,maiz,tomate y limón. Arroz:arroz blanco,sal,aceite.Salsa o guiso:cebolla blanca,tomate,ajo,comino,colorante alimentario.",
      en: "Typical dish consisting of a first course of broth and a second with beef ribs, pork ribs, hen, the three meats in sauce and garnish. Ingredients: Sancocho: plantain, cassava, potato, garlic, cumin, salt, coriander, beef ribs, pork ribs, hen. Salad garnish: lettuce, white onion, corn, tomato & lemon. Rice: white rice, salt, oil. Sauce or stew: white onion, tomato, garlic, cumin, food coloring.",
      de: "Typisches Gericht, das aus einem ersten Gang Brühe und einem zweiten mit Rinderrippchen, Schweinerippchen, Huhn, den drei Fleischsorten in Sauce und Beilage besteht. Zutaten: Sancocho: Kochbanane, Maniok, Kartoffel, Knoblauch, Kreuzkümmel, Salz, Koriander, Rinderrippchen, Schweinerippchen, Huhn. Salatgarnitur: Salat, weiße Zwiebel, Mais, Tomate & Zitrone. Reis: weißer Reis, Salz, Öl. Sauce oder Eintopf: weiße Zwiebel, Tomate, Knoblauch, Kreuzkümmel, Lebensmittelfarbe.",
      fr: "Plat typique composé d'un premier plat de bouillon et d'un second avec des côtes de bœuf, des côtes de porc, de la poule, les trois viandes en sauce et garniture. Ingrédients : sancocho : banane plantain, manioc, pomme de terre, ail, cumin, sel, coriandre, côtes de bœuf, côtes de porc, poule. Garniture de salade : laitue, oignon blanc, maïs, tomate & citron. Riz : riz blanc, sel, huile. Sauce ou ragoût : oignon blanc, tomate, ail, cumin, colorant alimentaire.",
    },
    image: IMG["main"],
  },
  {
    id: slug("Sancocho de costilla"),
    category: "main",
    name: "Sancocho de costilla",
    i18nNames: {
      es: "Sancocho de costilla",
      en: "Rib sancocho",
      de: "Sancocho mit Rippchen",
      fr: "Sancocho de côtes",
    },
    price: 17.00,
    descriptions: {
      es: "Plato tipico compuesto de un primer plato de caldo y un segundo con costilla de res en salsa y guarnición. Ingredientes:Sancocho:platano,yuca,papa,ajo,comino,sal,cilantro,costilla de res.Punta de ensalada:lechuga,cebolla blanca,maiz,tomate y limón. Arroz:arroz blanco,sal,aceite.Salsa o guiso:cebolla blanca,tomate,ajo,comino,colorante alimentario.",
      en: "Typical dish consisting of a first course of broth and a second with beef ribs in sauce and garnish. Ingredients: Sancocho: plantain, cassava, potato, garlic, cumin, salt, coriander, beef ribs. Salad garnish: lettuce, white onion, corn, tomato & lemon. Rice: white rice, salt, oil. Sauce or stew: white onion, tomato, garlic, cumin, food coloring.",
      de: "Typisches Gericht, das aus einem ersten Gang Brühe und einem zweiten mit Rinderrippchen in Sauce und Beilage besteht. Zutaten: Sancocho: Kochbanane, Maniok, Kartoffel, Knoblauch, Kreuzkümmel, Salz, Koriander, Rinderrippchen. Salatgarnitur: Salat, weiße Zwiebel, Mais, Tomate & Zitrone. Reis: weißer Reis, Salz, Öl. Sauce oder Eintopf: weiße Zwiebel, Tomate, Knoblauch, Kreuzkümmel, Lebensmittelfarbe.",
      fr: "Plat typique composé d'un premier plat de bouillon et d'un second avec des côtes de bœuf en sauce et garniture. Ingrédients : sancocho : banane plantain, manioc, pomme de terre, ail, cumin, sel, coriandre, côtes de bœuf. Garniture de salade : laitue, oignon blanc, maïs, tomate & citron. Riz : riz blanc, sel, huile. Sauce ou ragoût : oignon blanc, tomate, ail, cumin, colorant alimentaire.",
    },
    image: IMG["main"],
  },
  // === Nuevos MAIN solicitados ===
  {
    id: slug("Bacalao encebollado"),
    category: "main",
    name: "Bacalao encebollado",
    i18nNames: {
      es: "Bacalao encebollado",
      en: "Cod with onions",
      de: "Kabeljau mit Zwiebeln",
      fr: "Morue aux oignons",
    },
    price: 16.0,
    descriptions: {
      es: "Lomo de bacalao con cebolla confitada. Ingredientes:Lomo de bacalao, cebolla, aceite de oliva,pimiento rojo,tomate,ajo,laurel,tomillo,oregano,comino colorante alimentario,vino.Papa guisada.",
      en: "Cod loin with caramelized onions. Ingredients: cod loin, onion, olive oil, red pepper, tomato, garlic, bay leaf, thyme, oregano, cumin, food coloring, wine. Stewed potato.",
      de: "Kabeljaufilet mit geschmorten Zwiebeln. Zutaten: Kabeljaufilet, Zwiebel, Olivenöl, roter Paprika, Tomate, Knoblauch, Lorbeer, Thymian, Oregano, Kreuzkümmel, Lebensmittelfarbe, Wein. Geschmorte Kartoffel.",
      fr: "Filet de morue aux oignons confits. Ingrédients : filet de morue, oignon, huile d’olive, poivron rouge, tomate, ail, laurier, thym, origan, cumin, colorant alimentaire, vin. Pomme de terre mijotée.",
    },
    image: "img/platos/bacalao.jpg",
  },
  {
    id: slug("Pescado frito"),
    category: "main",
    name: "Pescado frito",
    i18nNames: {
      es: "Pescado frito(Dorada)",
      en: "Fried fish(Dorada)",
      de: "Frittierter Fisch",
      fr: "Poisson frit",
    },
    price: 19.50,
    descriptions: {
      es: "Pieza de pescado dorada y crujiente. Ingredientes:Pescado blanco (Dorada):sal,limón,comino. Ajo,aceite oliva,vinagre.Punta de ensalada:lechuga,cebolla blanca,maiz,zanahoria rallada, tomate y lim.Patacon.",
      en: "Golden, crispy fish piece. Ingredients: White fish (Dorada): salt, lemon, cumin. Garlic, olive oil, vinegar. Salad garnish: lettuce, white onion, corn, grated carrot, tomato & lemon. Patacón.",
      de: "Goldbraun und knusprig. Zutaten: Weißfisch (Dorada): Salz, Zitrone, Kreuzkümmel. Knoblauch, Olivenöl, Essig. Salatgarnitur: Salat, weiße Zwiebel, Mais, geriebene Karotte, Tomate & Zitrone. Patacón.",
      fr: "Pièce de poisson dorée et croustillante. Ingrédients : poisson blanc (Dorada) : sel, citron, cumin. Ail, huile d'olive, vinaigre. Garniture de salade : laitue, oignon blanc, maïs, carotte râpée, tomate et citron. Patacón.",
    },
    image: IMG["main"],
  },

  /* ---------- GRILL ---------- */
  {
    id: slug("Parrillada mixta"),
    category: "grill",
    name: "Parrillada mixta",
    i18nNames: {
      es: "Parrillada mixta",
      en: "Mixed grill",
      de: "Gemischter Grillteller",
      fr: "Grillade mixte",
    },
    price: 33.0,
    descriptions: {
      es: "Surtido de carnes a la brasa. Ingredientes:Entrecot de ternera, bistec de cerdo, chorizo parrillero,pollo .",
      en: "Assorted grilled meats. Ingredients: ribeye steak, pork steak, chorizo, chicken.",
      de: "Gemischte Grillfleischplatte. Zutaten: Rinderentrecôte, Schweinesteak, Chorizo, Hähnchen.",
      fr: "Assortiment de viandes grillées. Ingrédients : Entrecôte de veau, steak de porc, chorizo, poulet.",
    },
    image: "img/platos/parrillada.jpg",
  },
  {
    id: slug("Solomillo de cerdo"),
    category: "grill",
    name: "Solomillo de cerdo",
    i18nNames: {
      es: "Solomillo de cerdo",
      en: "Pork tenderloin",
      de: "Schweinefilet",
      fr: "Filet de porc",
    },
    price: 15.90,
    descriptions: {
      es: "A la plancha, jugoso. Ingredientes: solomillo de cerdo. Punta de ensalada: lechuga, cebolla blanca, maíz, zanahoria rallada, tomate, limón. Papas fritas.",
      en: "Griddled, juicy. Ingredients: pork tenderloin. Salad garnish: lettuce, white onion, corn, grated carrot, tomato, lemon. French fries.",
      de: "Von der Platte, saftig. Zutaten: Schweinefilet. Salatgarnitur: Kopfsalat, weiße Zwiebel, Mais, geriebene Karotte, Tomate, Zitrone. Pommes frites.",
      fr: "Saisi, juteux. Ingrédients : filet de porc. Garniture de salade : laitue, oignon blanc, maïs, carotte râpée, tomate, citron. Frites.",
    },
    image: "img/platos/solomillo-cerdo.jpg",
  },
  {
    id: slug("Entrecot de ternera"),
    category: "grill",
    name: "Entrecot de ternera",
    i18nNames: {
      es: "Entrecot de ternera",
      en: "Veal/Beef entrecôte",
      de: "Entrecôte (Rind/Veal)",
      fr: "Entrecôte (veau/boeuf)",
    },
    price: 18.0,
    descriptions: {
      es: "Al punto. Ingredientes: entrecot, sal, pimienta, aceite.",
      en: "To your liking. Ingredients: entrecôte, salt, pepper, oil.",
      de: "Nach Wunsch. Zutaten: Entrecôte, Salz, Pfeffer, Öl.",
      fr: "À la demande. Ingrédients : entrecôte, sel, poivre, huile.",
    },
    image: "img/platos/entrecot.jpg",
  },
  {
    id: slug("Secreto iberico"),
    category: "grill",
    name: "Secreto ibérico",
    i18nNames: {
      es: "Secreto ibérico",
      en: "Iberian pork 'secreto'",
      de: "Iberico Secreto",
      fr: "Secreto ibérique",
    },
    price: 15.0,
    descriptions: {
      es: "Muy jugoso. Ingredientes: Secreto ibérico, adobo. Punta de ensalada: lechuga, cebolla blanca, maíz, zanahoria rallada, tomate, limón. Papas fritas.",
      en: "Very juicy. Ingredients: Iberian pork, marinade. Salad garnish: lettuce, white onion, corn, grated carrot, tomato, lemon. French fries.",
      de: "Sehr saftig. Zutaten: Iberico Fleisch, Marinade. Salatgarnitur: Kopfsalat, weiße Zwiebel, Mais, geriebene Karotte, Tomate, Zitrone. Pommes frites.",
      fr: "Très juteux. Ingrédients : le secret ibérique, marinade. Garniture de salade : laitue, oignon blanc, maïs, carotte râpée, tomate, citron. Frites.",
    },
    image: IMG["grill"],
  },
  {
    id: slug("Chuleta de cerdo"),
    category: "grill",
    name: "Chuleta de cerdo",
    i18nNames: {
      es: "Chuleta de cerdo",
      en: "Pork chop",
      de: "Schweinekotelett",
      fr: "Côte de porc",
    },
    price: 17.90,
    descriptions: {
      es: "A la brasa con punta de ensalada y papas fritas naturales. Ingredientes: chuleta, sal, pimienta, aceite, ensalada , papas fritas.",
      en: "Grilled with a side salad and fries. Ingredients: chop, salt, pepper, oil, salad, fries.",
      de: "Von der Platte mit Beilage. Zutaten: Kotelett, Salz, Pfeffer, Öl, Salat, Pommes frites.",
      fr: "Poêlée avec garniture. Ingrédients : côte de porc, sel, poivre, huile, salade, frites.",
    },
    image: IMG["grill"],
  },
  {
    id: slug("Medio pollo - pollo entero"),
    category: "grill",
    name: "Medio pollo / pollo entero",
    i18nNames: {
      es: "Medio pollo / pollo entero",
      en: "Half chicken / whole chicken",
      de: "Halbes / ganzes Hähnchen",
      fr: "Demi-poulet / poulet entier",
    },
    priceHalf: 9.50,
    priceWhole: 14.80,
    descriptions: {
      es: "Medio pollo a la brasa con ensalada y papas fritas naturales. Pollo entero solo pollo. Ingredientes: pollo, sal, pimienta, ajo, aceite, ensalada, papas fritas.",
      en: "Half chicken from the grill with salad and fries. Whole chicken is served without garnish. Ingredients: chicken, salt, pepper, garlic, oil, salad, fries.",
      de: "Halbes Hähnchen vom Grill mit Salat und Pommes frites. Ganzes Hähnchen ohne Beilage. Zutaten: Hähnchen, Salz, Pfeffer, Knoblauch, Öl, Salat, Pommes frites.",
      fr: "Demi-poulet au gril avec salade et frites. Poulet entier sans garniture. Ingrédients : poulet, sel, poivre, ail, huile, salade, frites.",
    },
    image: "img/platos/pollo.jpg",
  },
  // === Nueva GRILL solicitada ===
  {
    id: slug("Grilled Picada Sazon from my Land"),
    category: "grill",
    name: "Picada a la brasa Sazón de mi Tierra",
    i18nNames: {
      es: "Parrillada-picada Sazón de mi Tierra",
      en: "Grilled Picada Sazón from my Land",
      de: "Gegrillte Picada „Sazón de mi Tierra“",
      fr: "Picada grillée « Sazón de mi Tierra »",
    },
    price: 42.90,
    descriptions: {
      es: "Surtido a la brasa para compartir. Ingredientes: Bistec de ternera, bistec de cerdo, pollo, chorizo antioqueño, chicharrones, chorizo parrilero, chuleta, arepa, patacones y pimientos.",
      en: "Grilled assortment to share. Ingredients: beef steak, pork steak, chicken, chorizo, pork rind, arepa, fried plantain & peppers.",
      de: "Gegrillte Auswahl zum Teilen. Zutaten: Rindersteak, Schweinesteak, Hähnchen, Chorizo, Schweinekrusten, Arepa, frittierte Kochbananen & Paprika.",
      fr: "Assortiment grillé à partager. Ingrédients : steak de bœuf, steak de porc, poulet, chorizo, couenne, arepa, banane plantain frite & poivrons.",
    },
    image: IMG["grill"],
  },

  /* ---------- DESSERT ---------- */
  {
    id: slug("Tarta de la abuela"),
    category: "dessert",
    name: "Tarta de la abuela",
    i18nNames: {
      es: "Tarta de la abuela",
      en: "Grandma's cake",
      de: "Omas Kuchen",
      fr: "Gâteau de grand-mère",
    },
    price: 5.00,
    descriptions: {
      es: "Casera con crema y galleta. Ingredientes: galleta, crema pastelera, cacao.",
      en: "Homemade with cream & biscuit. Ingredients: biscuit, custard, cocoa.",
      de: "Hausgemacht mit Creme & Keks. Zutaten: Keks, Vanillecreme, Kakao.",
      fr: "Maison, crème & biscuit. Ingrédients : biscuit, crème pâtissière, cacao.",
    },
    image: IMG["dessert"],
  },
  {
    id: slug("Quesillo"),
    category: "dessert",
    name: "Quesillo",
    i18nNames: { es: "Quesillo", en: "Quesillo", de: "Quesillo", fr: "Quesillo" },
    price: 5.00,
    descriptions: {
      es: "Flan de huevo suave. Ingredientes: leche,leche condensada,huevos,vainilla,caramelo y limón.",
      en: "Silky egg flan. Ingredients: milk, condensed milk, eggs, vanilla, caramel, and lemon.",
      de: "Zarter Eierflan. Zutaten: Milch, Kondensmilch, Eier, Vanille, Karamell und Zitrone.",
      fr: "Flan aux œufs onctueux. Ingrédients : lait, lait concentré, œufs, vanille, caramel et citron.",
    },
    image: IMG["dessert"],
  },
  {
    id: slug("Postres variados"),
    category: "dessert",
    name: "Postres variados",
    i18nNames: {
      es: "Postres variados",
      en: "Assorted desserts",
      de: "Verschiedene Desserts",
      fr: "Desserts variés",
    },
    price: 0,
    descriptions: {
      es: "Pregunta por el postre de hoy.",
      en: "Ask for today's dessert.",
      de: "Fragen Sie nach dem Dessert des Tages.",
      fr: "Demandez le dessert du jour.",
    },
    image: IMG["dessert"],
  },
  // {
  //   id: slug("Principe Alberto"),
  //   category: "dessert",
  //   name: "Príncipe Alberto",
  //   i18nNames: {
  //     es: "Príncipe Alberto",
  //     en: "Príncipe Alberto",
  //     de: "Príncipe Alberto",
  //     fr: "Príncipe Alberto",
  //   },
  //   price: 4.5,
  //   descriptions: {
  //     es: "Postre canario. Ingredientes: chocolate, almendra, bizcocho.",
  //     en: "Canarian dessert. Ingredients: chocolate, almond, sponge.",
  //     de: "Kanarisches Dessert. Zutaten: Schokolade, Mandel, Biskuit.",
  //     fr: "Dessert canarien. Ingrédients : chocolat, amande, biscuit.",
  //   },
  //   image: IMG["dessert"],
  // },
  // {
  //   id: slug("Pastel de elote con bocadillo"),
  //   category: "dessert",
  //   name: "Pastel de elote con bocadillo",
  //   i18nNames: {
  //     es: "Pastel de elote con bocadillo",
  //     en: "Corn cake with guava paste",
  //     de: "Maiskuchen mit Guavenpaste",
  //     fr: "Gâteau de maïs au bocadillo",
  //   },
  //   price: 4.5,
  //   descriptions: {
  //     es: "Bizcocho de maíz y guayaba. Ingredientes: maíz, huevo, leche, bocadillo (guayaba).",
  //     en: "Corn sponge & guava. Ingredients: corn, egg, milk, guava paste.",
  //     de: "Mais-Biskuit & Guave. Zutaten: Mais, Ei, Milch, Guavenpaste.",
  //     fr: "Biscuit de maïs & goyave. Ingrédients : maïs, œuf, lait, pâte de goyave.",
  //   },
  //   image: IMG["dessert"],
  // },
  // {
  //   id: slug("Mousse de maracuya"),
  //   category: "dessert",
  //   name: "Mousse de maracuyá",
  //   i18nNames: {
  //     es: "Mousse de maracuyá",
  //     en: "Passion fruit mousse",
  //     de: "Maracuja-Mousse",
  //     fr: "Mousse au fruit de la passion",
  //   },
  //   price: 3.5,
  //   descriptions: {
  //     es: "Ligera y afrutada. Ingredientes: maracuyá, nata, azúcar, gelatina.",
  //     en: "Light & fruity. Ingredients: passion fruit, cream, sugar, gelatin.",
  //     de: "Leicht & fruchtig. Zutaten: Maracuja, Sahne, Zucker, Gelatine.",
  //     fr: "Légère & fruitée. Ingrédients : fruit de la passion, crème, sucre, gélatine.",
  //   },
  //   image: IMG["dessert"],
  // },

  /* ---------- DRINKS: Soft drinks ---------- */
  {
    id: slug("Coca-Cola"),
    category: "drinks-soft",
    name: "Coca-Cola (normal/diet)",
    i18nNames: {
      es: "Coca-Cola (normal/diet)",
      en: "Coca-Cola (regular/diet)",
      de: "Coca-Cola (normal/light)",
      fr: "Coca-Cola (classique/light)",
    },
    price: 2.50, // actualizado
    descriptions: {
      es: "Refresco carbonatado. Ingredientes: agua, azúcar/edulcorante, CO₂, aromas.",
      en: "Carbonated soft drink. Ingredients: water, sugar/sweetener, CO₂, flavorings.",
      de: "Kohlensäurehaltiges Erfrischungsgetränk. Zutaten: Wasser, Zucker/Süßstoff, CO₂, Aromen.",
      fr: "Boisson gazeuse. Ingrédients : eau, sucre/édulcorant, CO₂, arômes.",
    },
    image: IMG["drinks-soft"],
  },
  {
    id: slug("Fanta"),
    category: "drinks-soft",
    name: "Fanta (naranja/limón)",
    i18nNames: {
      es: "Fanta (naranja/limón)",
      en: "Fanta (orange/lemon)",
      de: "Fanta (Orange/Zitrone)",
      fr: "Fanta (orange/citron)",
    },
    price: 2.50, // actualizado
    descriptions: {
      es: "Refresco de sabor. Ingredientes: agua, azúcar, CO₂, aromas cítricos.",
      en: "Flavoured soda. Ingredients: water, sugar, CO₂, citrus flavorings.",
      de: "Limonade mit Geschmack. Zutaten: Wasser, Zucker, CO₂, Zitrusaromen.",
      fr: "Soda aromatisé. Ingrédients : eau, sucre, CO₂, arômes d’agrumes.",
    },
    image: IMG["drinks-soft"],
  },
  {
    id: slug("Sprite"),
    category: "drinks-soft",
    name: "Sprite",
    i18nNames: { es: "Sprite", en: "Sprite", de: "Sprite", fr: "Sprite" },
    price: 2.5, // actualizado
    descriptions: {
      es: "Refresco lima-limón. Ingredientes: agua, azúcar, CO₂, aromas.",
      en: "Lemon-lime soda. Ingredients: water, sugar, CO₂, flavorings.",
      de: "Zitronenlimonade. Zutaten: Wasser, Zucker, CO₂, Aromen.",
      fr: "Soda citron-limette. Ingrédients : eau, sucre, CO₂, arômes.",
    },
    image: IMG["drinks-soft"],
  },
  {
    id: slug("Fuze Tea Mango Pina"),
    category: "drinks-soft",
    name: "Fuze Tea (mango-piña)",
    i18nNames: {
      es: "Fuze Tea (mango-piña)",
      en: "Fuze Tea (mango-pineapple)",
      de: "Fuze Tea (Mango-Ananas)",
      fr: "Fuze Tea (mangue-ananas)",
    },
    price: 2.5, // actualizado
    descriptions: {
      es: "Té frío saborizado. Ingredientes: agua, extracto de té, azúcar, aromas.",
      en: "Flavoured iced tea. Ingredients: water, tea extract, sugar, flavorings.",
      de: "Aromatisierter Eistee. Zutaten: Wasser, Tee-Extrakt, Zucker, Aromen.",
      fr: "Thé glacé aromatisé. Ingrédients : eau, extrait de thé, sucre, arômes.",
    },
    image: IMG["drinks-soft"],
  },
  {
    id: slug("Royal Bliss"),
    category: "drinks-soft",
    name: "Royal Bliss (Classic/Berry)",
    i18nNames: {
      es: "Royal Bliss (Classic/Berry)",
      en: "Royal Bliss (Classic/Berry)",
      de: "Royal Bliss (Classic/Berry)",
      fr: "Royal Bliss (Classic/Berry)",
    },
    price: 2.5, // actualizado
    descriptions: {
      es: "Mixer refrescante. Ingredientes: agua carbonatada, azúcar, aromas.",
      en: "Refreshing mixer. Ingredients: carbonated water, sugar, flavorings.",
      de: "Erfrischender Mixer. Zutaten: kohlensäurehaltiges Wasser, Zucker, Aromen.",
      fr: "Mixer rafraîchissant. Ingrédients : eau gazeuse, sucre, arômes.",
    },
    image: IMG["drinks-soft"],
  },
  {
    id: slug("Red Bull"),
    category: "drinks-soft",
    name: "Red Bull",
    i18nNames: {
      es: "Red Bull",
      en: "Red Bull",
      de: "Red Bull",
      fr: "Red Bull",
    },
    price: 2.5, // añadido y actualizado
    descriptions: {
      es: "Bebida energética.",
      en: "Energy drink.",
      de: "Energydrink.",
      fr: "Boisson énergisante.",
    },
    image: IMG["drinks-soft"],
  },
  {
    id: slug("Hit"),
    category: "drinks-soft",
    name: "Bebida Hit (colombiana)",
    i18nNames: {
      es: "Bebida Hit (colombiana)",
      en: "Hit drink (Colombian)",
      de: "Hit Getränk (kolumbianisch)",
      fr: "Boisson Hit (colombienne)",
    },
    price: 2.0, // añadido y actualizado
    descriptions: {
      es: "Bebida de fruta colombiana.",
      en: "Colombian fruit drink.",
      de: "Kolumbianisches Fruchtgetränk.",
      fr: "Boisson de fruit colombienne.",
    },
    image: IMG["drinks-soft"],
  },
  {
    id: slug("Postobon Uva"),
    category: "drinks-soft",
    name: "Postobón Uva",
    i18nNames: {
      es: "Postobón Uva",
      en: "Postobón Grape",
      de: "Postobón Traube",
      fr: "Postobón Raisin",
    },
    price: 2.5, // actualizado
    descriptions: {
      es: "Refresco colombiano de uva. Ingredientes: agua, azúcar, CO₂, aromas de uva.",
      en: "Colombian grape soda. Ingredients: water, sugar, CO₂, grape flavorings.",
      de: "Kolumbianische Traubenlimonade. Zutaten: Wasser, Zucker, CO₂, Traubenaromen.",
      fr: "Soda colombien au raisin. Ingrédients : eau, sucre, CO₂, arômes de raisin.",
    },
    image: "img/platos/postobon-uva.jpg",
  },
  {
    id: slug("Postobon Manzana"),
    category: "drinks-soft",
    name: "Postobón Manzana",
    i18nNames: {
      es: "Postobón Manzana",
      en: "Postobón Apple",
      de: "Postobón Apfel",
      fr: "Postobón Pomme",
    },
    price: 2.5, // actualizado
    descriptions: {
      es: "Refresco colombiano de manzana. Ingredientes: agua, azúcar, CO₂, aromas de manzana.",
      en: "Colombian apple soda. Ingredients: water, sugar, CO₂, apple flavorings.",
      de: "Kolumbianische Apfellimonade. Zutaten: Wasser, Zucker, CO₂, Apfelaromen.",
      fr: "Soda colombien à la pomme. Ingrédients : eau, sucre, CO₂, arômes de pomme.",
    },
    image: "img/platos/postobon-manzana.jpg",
  },
  {
    id: slug("Colombiana"),
    category: "drinks-soft",
    name: "Colombiana",
    i18nNames: {
      es: "Colombiana",
      en: "Colombiana",
      de: "Colombiana",
      fr: "Colombiana",
    },
    price: 2.5, // actualizado
    descriptions: {
      es: "Refresco colombiano tradicional. Ingredientes: agua, azúcar, CO₂, aromas.",
      en: "Traditional Colombian soda. Ingredients: water, sugar, CO₂, flavorings.",
      de: "Traditionelle kolumbianische Limonade. Zutaten: Wasser, Zucker, CO₂, Aromen.",
      fr: "Soda colombien traditionnel. Ingrédients : eau, sucre, CO₂, arômes.",
    },
    image: "img/platos/colombiana.jpg",
  },
  {
    id: slug("Zumo"),
    category: "drinks-soft",
    name: "Zumo (mango/melocotón)",
    i18nNames: {
      es: "Zumo (mango/melocotón)",
      en: "Juice (mango/peach)",
      de: "Saft (Mango/Pfirsich)",
      fr: "Jus (mangue/pêche)",
    },
    price: 2.0, // actualizado
    descriptions: {
      es: "Jugo de fruta. Ingredientes: fruta, agua, azúcar (según sabor).",
      en: "Fruit juice. Ingredients: fruit, water, sugar (varies).",
      de: "Fruchtsaft. Zutaten: Frucht, Wasser, Zucker (variabel).",
      fr: "Jus de fruits. Ingrédients : fruit, eau, sucre (variable).",
    },
    image: IMG["drinks-soft"],
  },

  /* ---------- DRINKS: Beers ---------- */
  {
    id: slug("Dorada especial"),
    category: "drinks-beer",
    name: "Dorada Especial",
    i18nNames: {
      es: "Dorada Especial",
      en: "Dorada Especial",
      de: "Dorada Especial",
      fr: "Dorada Especial",
    },
    price: 2.0,
    descriptions: {
      es: "Lager canaria. Ingredientes: agua, malta de cebada, lúpulo.",
      en: "Canarian lager. Ingredients: water, barley malt, hops.",
      de: "Kanarisches Lager. Zutaten: Wasser, Gerstenmalz, Hopfen.",
      fr: "Lager canarienne. Ingrédients : eau, malt d’orge, houblon.",
    },
    image: IMG["drinks-beer"],
  },
  {
    id: slug("Dorada especial grande"),
    category: "drinks-beer",
    name: "Dorada Especial (grande)",
    i18nNames: {
      es: "Dorada Especial (grande)",
      en: "Dorada Especial (large)",
      de: "Dorada Especial (groß)",
      fr: "Dorada Especial (grande)",
    },
    price: 3.5,
    descriptions: {
      es: "Formato grande. Ingredientes: agua, malta, lúpulo.",
      en: "Large bottle. Ingredients: water, malt, hops.",
      de: "Große Flasche. Zutaten: Wasser, Malz, Hopfen.",
      fr: "Grand format. Ingrédients : eau, malt, houblon.",
    },
    image: IMG["drinks-beer"],
  },
  {
    id: slug("Dorada pilsen"),
    category: "drinks-beer",
    name: "Dorada Pilsen",
    i18nNames: {
      es: "Dorada Pilsen",
      en: "Dorada Pilsen",
      de: "Dorada Pilsen",
      fr: "Dorada Pilsen",
    },
    price: 2.2,
    descriptions: {
      es: "Pilsen canaria. Ingredientes: agua, malta, lúpulo.",
      en: "Canarian pilsner. Ingredients: water, malt, hops.",
      de: "Kanarisches Pils. Zutaten: Wasser, Malz, Hopfen.",
      fr: "Pils canarienne. Ingrédients : eau, malt, houblon.",
    },
    image: IMG["drinks-beer"],
  },
  {
    id: slug("Dorada tostada"),
    category: "drinks-beer",
    name: "Dorada Especial Tostada",
    i18nNames: {
      es: "Dorada Especial Tostada",
      en: "Dorada Especial Toasted",
      de: "Dorada Especial Toasted",
      fr: "Dorada Especial Toasted",
    },
    price: 2.5,
    descriptions: {
      es: "Malta tostada. Ingredientes: agua, malta tostada, lúpulo.",
      en: "Toasted malt profile. Ingredients: water, toasted malt, hops.",
      de: "Geröstetes Malzprofil. Zutaten: Wasser, Röstmalz, Hopfen.",
      fr: "Profil malté torréfié. Ingrédients : eau, malt torréfié, houblon.",
    },
    image: IMG["drinks-beer"],
  },
  {
    id: slug("Dorada 0"),
    category: "drinks-beer",
    name: "Dorada sin alcohol",
    i18nNames: {
      es: "Dorada sin alcohol",
      en: "Dorada alcohol-free",
      de: "Dorada alkoholfrei",
      fr: "Dorada sans alcool",
    },
    price: 2.0,
    descriptions: {
      es: "Sin alcohol. Ingredientes: agua, malta, lúpulo.",
      en: "Alcohol-free. Ingredients: water, malt, hops.",
      de: "Alkoholfrei. Zutaten: Wasser, Malz, Hopfen.",
      fr: "Sans alcool. Ingrédients : eau, malt, houblon.",
    },
    image: IMG["drinks-beer"],
  },
  {
    id: slug("Dorada 0 limon"),
    category: "drinks-beer",
    name: "Dorada sin alcohol limón",
    i18nNames: {
      es: "Dorada sin alcohol limón",
      en: "Dorada alcohol-free lemon",
      de: "Dorada alkoholfrei Zitrone",
      fr: "Dorada sans alcool citron",
    },
    price: 2.2,
    descriptions: {
      es: "Con limón. Ingredientes: cerveza 0.0, limón, azúcar.",
      en: "Lemon blend. Ingredients: 0.0 beer, lemon, sugar.",
      de: "Mit Zitrone. Zutaten: 0.0 Bier, Zitrone, Zucker.",
      fr: "Citronnée. Ingrédients : bière 0.0, citron, sucre.",
    },
    image: IMG["drinks-beer"],
  },
  {
    id: slug("Corona"),
    category: "drinks-beer",
    name: "Corona",
    i18nNames: { es: "Corona", en: "Corona", de: "Corona", fr: "Corona" },
    price: 3.5,
    descriptions: {
      es: "Cerveza internacional. Ingredientes: agua, malta, lúpulo.",
      en: "International lager. Ingredients: water, malt, hops.",
      de: "Internationales Lagerbier. Zutaten: Wasser, Malz, Hopfen.",
      fr: "Bière blonde internationale. Ingrédients : eau, malt, houblon.",
    },
    image: IMG["drinks-beer"],
  },

  /* ---------- DRINKS: Waters ---------- */
  {
    id: slug("Agua pequena"),
    category: "drinks-water",
    name: "Agua (botella pequeña)",
    i18nNames: {
      es: "Agua (pequeña)",
      en: "Water (small bottle)",
      de: "Wasser (klein)",
      fr: "Eau (petite bouteille)",
    },
    price: 1.2, // actualizado
    descriptions: {
      es: "Agua mineral. Ingredientes: agua.",
      en: "Mineral water. Ingredients: water.",
      de: "Mineralwasser. Zutaten: Wasser.",
      fr: "Eau minérale. Ingrédients : eau.",
    },
    image: IMG["drinks-water"],
  },
  {
    id: slug("Agua grande"),
    category: "drinks-water",
    name: "Agua (botella grande)",
    i18nNames: {
      es: "Agua (grande)",
      en: "Water (large bottle)",
      de: "Wasser (groß)",
      fr: "Eau (grande bouteille)",
    },
    price: 2.5, // actualizado
    descriptions: {
      es: "Agua mineral. Ingredientes: agua.",
      en: "Mineral water. Ingredients: water.",
      de: "Mineralwasser. Zutaten: Wasser.",
      fr: "Eau minérale. Ingrédients : eau.",
    },
    image: IMG["drinks-water"],
  },
  {
    id: slug("Agua con gas"),
    category: "drinks-water",
    name: "Agua con gas",
    i18nNames: {
      es: "Agua con gas",
      en: "Sparkling water",
      de: "Sprudelwasser",
      fr: "Eau gazeuse",
    },
    price: 1.5,
    descriptions: {
      es: "Con burbujas. Ingredientes: agua, CO₂.",
      en: "Bubbly. Ingredients: water, CO₂.",
      de: "Mit Kohlensäure. Zutaten: Wasser, CO₂.",
      fr: "Pétillante. Ingrédients : eau, CO₂.",
    },
    image: IMG["drinks-water"],
  },

  /* ---------- DRINKS: Coffee & infusions ---------- */
  {
    id: slug("Cafe expreso"),
    category: "drinks-coffee",
    name: "Café expreso",
    i18nNames: {
      es: "Café expreso",
      en: "Espresso",
      de: "Espresso",
      fr: "Expresso",
    },
    price: 1.2,
    descriptions: {
      es: "Corto y aromático. Ingredientes: café arábica, agua.",
      en: "Short & aromatic. Ingredients: arabica coffee, water.",
      de: "Kurz & aromatisch. Zutaten: Arabica-Kaffee, Wasser.",
      fr: "Court & aromatique. Ingrédients : café arabica, eau.",
    },
    image: IMG["drinks-coffee"],
  },
   {
    id: slug("Americano"),
    category: "drinks-coffee",
    name: "Americano",
    i18nNames: {
      es: "Americano",
      en: "Americano",
      de: "Americano",
      fr: "Americano",
    },
    price: 1.50,
    descriptions: {
      es: "Corto y aromático. Ingredientes: café arábica, agua.",
      en: "Short & aromatic. Ingredients: arabica coffee, water.",
      de: "Kurz & aromatisch. Zutaten: Arabica-Kaffee, Wasser.",
      fr: "Court & aromatique. Ingrédients : café arabica, eau.",
    },
    image: IMG["drinks-coffee"],
  }, {
    id: slug("Capuchino"),
    category: "drinks-coffee",
    name: "Capuchino",
    i18nNames: {
      es: "Capuchino",
      en: "Capuchino",
      de: "Capuchino",
      fr: "Capuchino",
    },
    price: 1.70,
    descriptions: {
      es: "Corto y aromático. Ingredientes: café arábica, agua.",
      en: "Short & aromatic. Ingredients: arabica coffee, water.",
      de: "Kurz & aromatisch. Zutaten: Arabica-Kaffee, Wasser.",
      fr: "Court & aromatique. Ingrédients : café arabica, eau.",
    },
    image: IMG["drinks-coffee"],
  },
  {
    id: slug("Cafe cortado"),
    category: "drinks-coffee",
    name: "Café cortado",
    i18nNames: {
      es: "Café cortado",
      en: "Macchiato",
      de: "Cortado",
      fr: "Cortado",
    },
    price: 1.3,
    descriptions: {
      es: "Con un toque de leche. Ingredientes: espresso, leche.",
      en: "Dash of milk. Ingredients: espresso, milk.",
      de: "Mit Milchschuss. Zutaten: Espresso, Milch.",
      fr: "Nuage de lait. Ingrédients : expresso, lait.",
    },
    image: IMG["drinks-coffee"],
  },
  {
    id: slug("Cafe bombon"),
    category: "drinks-coffee",
    name: "Café bombón",
    i18nNames: {
      es: "Café bombón",
      en: "Bombón coffee",
      de: "Kaffee mit Kondensmilch",
      fr: "Café bombón",
    },
    price: 1.4,
    descriptions: {
      es: "Con leche condensada. Ingredientes: espresso, leche condensada.",
      en: "With condensed milk. Ingredients: espresso, condensed milk.",
      de: "Mit Kondensmilch. Zutaten: Espresso, Kondensmilch.",
      fr: "Avec lait concentré. Ingrédients : expresso, lait concentré.",
    },
    image: IMG["drinks-coffee"],
  },
  {
    id: slug("Cafe con leche"),
    category: "drinks-coffee",
    name: "Café con leche",
    i18nNames: {
      es: "Café con leche",
      en: "Coffee with milk",
      de: "Kaffee mit Milch",
      fr: "Café au lait",
    },
    price: 1.8,
    descriptions: {
      es: "Clásico suave. Ingredientes: café, leche.",
      en: "Smooth classic. Ingredients: coffee, milk.",
      de: "Sanfter Klassiker. Zutaten: Kaffee, Milch.",
      fr: "Classique doux. Ingrédients : café, lait.",
    },
    image: IMG["drinks-coffee"],
  },
  {
    id: slug("Leche y leche"),
    category: "drinks-coffee",
    name: "Café leche y leche",
    i18nNames: {
      es: "Café leche y leche",
      en: "Milk & milk coffee",
      de: "Kaffee mit Milch & Kondensmilch",
      fr: "Café lait & lait concentré",
    },
    price: 1.8,
    descriptions: {
      es: "Con leche y condensada. Ingredientes: café, leche, leche condensada.",
      en: "Milk & condensed milk. Ingredients: coffee, milk, condensed milk.",
      de: "Mit Milch & Kondensmilch. Zutaten: Kaffee, Milch, Kondensmilch.",
      fr: "Lait & lait concentré. Ingrédients : café, lait, lait concentré.",
    },
    image: IMG["drinks-coffee"],
  },
  {
    id: slug("Descafeinado"),
    category: "drinks-coffee",
    name: "Café descafeinado",
    i18nNames: {
      es: "Café descafeinado",
      en: "Decaf coffee",
      de: "Entkoffeinierter Kaffee",
      fr: "Café décaféiné",
    },
    price: 1.2,
    descriptions: {
      es: "Sin cafeína. Ingredientes: café descafeinado, agua.",
      en: "Caffeine-free. Ingredients: decaf coffee, water.",
      de: "Koffeinfrei. Zutaten: entkoffeinierter Kaffee, Wasser.",
      fr: "Sans caféine. Ingrédients : café décaféiné, eau.",
    },
    image: IMG["drinks-coffee"],
  },
  {
    id: slug("Descafeinado con leche"),
    category: "drinks-coffee",
    name: "Descafeinado con leche",
    i18nNames: {
      es: "Descafeinado con leche",
      en: "Decaf with milk",
      de: "Entkoffeiniert mit Milch",
      fr: "Décaféiné au lait",
    },
    price: 2.0,
    descriptions: {
      es: "Suave y cremoso. Ingredientes: decaf, leche.",
      en: "Smooth & creamy. Ingredients: decaf, milk.",
      de: "Sanft & cremig. Zutaten: entkoffeinierter Kaffee, Milch.",
      fr: "Doux & crémeux. Ingrédients : décaféiné, lait.",
    },
    image: IMG["drinks-coffee"],
  },
  {
    id: slug("Barraquito"),
    category: "drinks-coffee",
    name: "Barraquito",
    i18nNames: { es: "Barraquito", en: "Barraquito", de: "Barraquito", fr: "Barraquito" },
    price: 3.0,
    descriptions: {
      es: "Café canario en capas. Ingredientes: espresso, leche, leche condensada, licor, canela, limón.",
      en: "Layered Canarian coffee. Ingredients: espresso, milk, condensed milk, liqueur, cinnamon, lemon.",
      de: "Kanarischer Schichtkaffee. Zutaten: Espresso, Milch, Kondensmilch, Likör, Zimt, Zitrone.",
      fr: "Café canarien en couches. Ingrédients : expresso, lait, lait concentré, liqueur, cannelle, citron.",
    },
    image: IMG["drinks-coffee"],
  },
  {
    id: slug("Infusiones"),
    category: "drinks-coffee",
    name: "Infusiones variadas",
    i18nNames: {
      es: "Infusiones variadas",
      en: "Various infusions",
      de: "Verschiedene Tees",
      fr: "Infusions variées",
    },
    price: 2.0,
    descriptions: {
      es: "Selección de tés. Ingredientes: mezcla de hierbas/hojas.",
      en: "Selection of teas. Ingredients: mixed herbs/leaves.",
      de: "Teeauswahl. Zutaten: Kräuter-/Blattmischung.",
      fr: "Sélection de thés. Ingrédients : mélange d’herbes/feuilles.",
    },
    image: IMG["drinks-coffee"],
  },

  /* ---------- DRINKS: Spirits & mixers (con 2 precios) ---------- */
  {
    id: slug("Johnnie Red"),
    category: "drinks-liquor",
    name: "Johnnie Walker Red Label",
    i18nNames: {
      es: "Johnnie Walker Red Label",
      en: "Johnnie Walker Red Label",
      de: "Johnnie Walker Red Label",
      fr: "Johnnie Walker Black Label",
    },
    priceShot: 2.0, priceGlass: 4.0, // deja vacío si aún no tienes precios
    descriptions: {
      es: "Blended Scotch. Ingredientes: whisky de malta y grano.",
      en: "Blended Scotch. Ingredients: malt & grain whiskies.",
      de: "Blended Scotch. Zutaten: Malt- & Grain-Whiskys.",
      fr: "Blended Scotch. Ingrédients : whiskies de malt et de grain.",
    },
    image: IMG["drinks-liquor"],
  },
  {
    id: slug("Johnnie Black"),
    category: "drinks-liquor",
    name: "Johnnie Walker Black Label",
    i18nNames: {
      es: "Johnnie Walker Black Label",
      en: "Johnnie Walker Black Label",
      de: "Johnnie Walker Black Label",
      fr: "Johnnie Walker Black Label",
    },
    priceShot: 2.0, priceGlass: 4.5,
    descriptions: {
      es: "Añejo escocés. Ingredientes: mezcla de whiskies.",
      en: "Aged Scotch. Ingredients: blended whiskies.",
      de: "Gereifter Scotch. Zutaten: Blended Whiskys.",
      fr: "Scotch vieilli. Ingrédients : whiskies assemblés.",
    },
    image: IMG["drinks-liquor"],
  },
  {
    id: slug("Chivas"),
    category: "drinks-liquor",
    name: "Chivas",
    i18nNames: { es: "Chivas", en: "Chivas", de: "Chivas", fr: "Chivas" },
    priceGlass: 5.0,
    descriptions: {
      es: "Whisky blended. Ingredientes: whiskies de malta y grano.",
      en: "Blended whisky. Ingredients: malt & grain whiskies.",
      de: "Blended Whisky. Zutaten: Malt- & Grain-Whiskys.",
      fr: "Whisky blend. Ingrédients : whiskies de malt et de grain.",
    },
    image: IMG["drinks-liquor"],
  },
  {
    id: slug("Buchanans"),
    category: "drinks-liquor",
    name: "Buchanan’s",
    i18nNames: {
      es: "Buchanan’s",
      en: "Buchanan’s",
      de: "Buchanan’s",
      fr: "Buchanan’s",
    },
    priceGlass: 6.0,
    descriptions: {
      es: "Scotch blended. Ingredientes: whiskies de malta y grano.",
      en: "Blended Scotch. Ingredients: malt & grain whiskies.",
      de: "Blended Scotch. Zutaten: Malt- & Grain-Whiskys.",
      fr: "Blended Scotch. Ingrédients : whiskies de malt et de grain.",
    },
    image: IMG["drinks-liquor"],
  },
  {
    id: slug("Gordons"),
    category: "drinks-liquor",
    name: "Gordon’s",
    i18nNames: { es: "Gordon’s", en: "Gordon’s", de: "Gordon’s", fr: "Gordon’s" },
    priceGlass: 4.0,
    descriptions: {
      es: "Ginebra clásica. Ingredientes: destilado de grano, enebro, botánicos.",
      en: "Classic gin. Ingredients: grain spirit, juniper, botanicals.",
      de: "Klassischer Gin. Zutaten: Getreidealkohol, Wacholder, Botanicals.",
      fr: "Gin classique. Ingrédients : alcool de grain, genévrier, botaniques.",
    },
    image: IMG["drinks-liquor"],
  },
  {
    id: slug("Hendricks"),
    category: "drinks-liquor",
    name: "Hendrick’s",
    i18nNames: { es: "Hendrick’s", en: "Hendrick’s", de: "Hendrick’s", fr: "Hendrick’s" },
    priceGlass: 6.0,
    descriptions: {
      es: "Ginebra premium. Ingredientes: botánicos, pepino, rosa.",
      en: "Premium gin. Ingredients: botanicals, cucumber, rose.",
      de: "Premium-Gin. Zutaten: Botanicals, Gurke, Rose.",
      fr: "Gin premium. Ingrédients : botaniques, concombre, rose.",
    },
    image: IMG["drinks-liquor"],
  },
  {
    id: slug("Arehucas"),
    category: "drinks-liquor",
    name: "Arehucas",
    i18nNames: { es: "Arehucas", en: "Arehucas", de: "Arehucas", fr: "Arehucas" },
    priceGlass: 4.0,
    descriptions: {
      es: "Ron canario. Ingredientes: melaza de caña, envejecimiento.",
      en: "Canarian rum. Ingredients: cane molasses, aging.",
      de: "Kanarischer Rum. Zutaten: Zuckerrohrmelasse, Reifung.",
      fr: "Rhum canarien. Ingrédients : mélasse de canne, vieillissement.",
    },
    image: IMG["drinks-liquor"],
  },
  {
    id: slug("Havana 3"),
    category: "drinks-liquor",
    name: "Havana 3 años",
    i18nNames: {
      es: "Havana 3 años",
      en: "Havana 3 years",
      de: "Havana 3 Jahre",
      fr: "Havana 3 ans",
    },
    priceShot: 2.0, priceGlass: 4.5,
    descriptions: {
      es: "Ron cubano. Ingredientes: melaza, añejamiento 3 años.",
      en: "Cuban rum. Ingredients: molasses, 3-year aging.",
      de: "Kubanischer Rum. Zutaten: Melasse, 3 Jahre Reife.",
      fr: "Rhum cubain. Ingrédients : mélasse, vieillissement 3 ans.",
    },
    image: IMG["drinks-liquor"],
  },
  {
    id: slug("Ron Viejo de Caldas"),
    category: "drinks-liquor",
    name: "Ron Viejo de Caldas",
    i18nNames: {
      es: "Ron Viejo de Caldas",
      en: "Ron Viejo de Caldas",
      de: "Ron Viejo de Caldas",
      fr: "Ron Viejo de Caldas",
    },
    priceGlass: 4.5,
    descriptions: {
      es: "Ron colombiano. Ingredientes: melaza de caña, añejamiento.",
      en: "Colombian rum. Ingredients: cane molasses, aging.",
      de: "Kolumbianischer Rum. Zutaten: Rohrmelasse, Reifung.",
      fr: "Rhum colombien. Ingrédients : mélasse de canne, vieillissement.",
    },
    image: IMG["drinks-liquor"],
  },
  {
    id: slug("Smirnoff Red"),
    category: "drinks-liquor",
    name: "Smirnoff Red",
    i18nNames: {
      es: "Smirnoff Red",
      en: "Smirnoff Red",
      de: "Smirnoff Red",
      fr: "Smirnoff Red",
    },
    priceShot: 2.0, priceGlass: 4.5,
    descriptions: {
      es: "Vodka clásico. Ingredientes: alcohol de grano, agua.",
      en: "Classic vodka. Ingredients: grain spirit, water.",
      de: "Klassischer Wodka. Zutaten: Getreidealkohol, Wasser.",
      fr: "Vodka classique. Ingrédients : alcool de grain, eau.",
    },
    image: IMG["drinks-liquor"],
  },
  {
    id: slug("Aguardiente rojo"),
    category: "drinks-liquor",
    name: "Aguardiente Antioqueño (rojo)",
    i18nNames: {
      es: "Aguardiente Antioqueño (rojo)",
      en: "Aguardiente Antioqueño (red)",
      de: "Aguardiente Antioqueño (rot)",
      fr: "Aguardiente Antioqueño (rouge)",
    },
    priceShot: 2.0,
    descriptions: {
      es: "Anisado colombiano. Ingredientes: alcohol, anís, azúcar.",
      en: "Colombian anis spirit. Ingredients: alcohol, anise, sugar.",
      de: "Kolumbianischer Anisschnaps. Zutaten: Alkohol, Anis, Zucker.",
      fr: "Spiritueux anisé colombien. Ingrédients : alcool, anis, sucre.",
    },
    image: IMG["drinks-liquor"],
  },
  {
    id: slug("Aguardiente amarillo"),
    category: "drinks-liquor",
    name: "Aguardiente Antioqueño (amarillo)",
    i18nNames: {
      es: "Aguardiente Antioqueño (amarillo)",
      en: "Aguardiente Antioqueño (yellow)",
      de: "Aguardiente Antioqueño (gelb)",
      fr: "Aguardiente Antioqueño (jaune)",
    },
    priceShot: 2.0,
    descriptions: {
      es: "Anisado colombiano. Ingredientes: alcohol, anís, azúcar.",
      en: "Colombian anis spirit. Ingredients: alcohol, anise, sugar.",
      de: "Kolumbianischer Anisschnaps. Zutaten: Alkohol, Anis, Zucker.",
      fr: "Spiritueux anisé colombien. Ingrédients : alcool, anis, sucre.",
    },
    image: IMG["drinks-liquor"],
  },
  {
    id: slug("Aguardiente azul"),
    category: "drinks-liquor",
    name: "Aguardiente Antioqueño (azul)",
    i18nNames: {
      es: "Aguardiente Antioqueño (azul)",
      en: "Aguardiente Antioqueño (blue)",
      de: "Aguardiente Antioqueño (blau)",
      fr: "Aguardiente Antioqueño (bleu)",
    },
    priceShot: 2.0,
    descriptions: {
      es: "Anisado colombiano. Ingredientes: alcohol, anís, azúcar.",
      en: "Colombian anis spirit. Ingredients: alcohol, anise, sugar.",
      de: "Kolumbianischer Anisschnaps. Zutaten: Alkohol, Anis, Zucker.",
      fr: "Spiritueux anisé colombien. Ingrédients : alcool, anis, sucre.",
    },
    image: IMG["drinks-liquor"],
  },
  {
    id: slug("Aguardiente del Valle"),
    category: "drinks-liquor",
    name: "Aguardiente del Valle",
    i18nNames: {
      es: "Aguardiente del Valle",
      en: "Aguardiente del Valle",
      de: "Aguardiente del Valle",
      fr: "Aguardiente del Valle",
    },
    priceShot: 2.0,
    descriptions: {
      es: "Aguardiente vallecaucano. Ingredientes: alcohol, anís, azúcar.",
      en: "Anis spirit from Valle del Cauca. Ingredients: alcohol, anise, sugar.",
      de: "Anisschnaps aus Valle del Cauca. Zutaten: Alkohol, Anis, Zucker.",
      fr: "Spiritueux anisé du Valle del Cauca. Ingrédients : alcool, anis, sucre.",
    },
    image: IMG["drinks-liquor"],
  },
  {
    id: slug("Jagermeister"),
    category: "drinks-liquor",
    name: "Jägermeister",
    i18nNames: { es: "Jägermeister", en: "Jägermeister", de: "Jägermeister", fr: "Jägermeister" },
    priceShot: 2.0, priceGlass: 4.0,
    descriptions: {
      es: "Licor de hierbas. Ingredientes: macerado de hierbas, especias.",
      en: "Herbal liqueur. Ingredients: herbs & spices maceration.",
      de: "Kräuterlikör. Zutaten: Kräuter- & Gewürzauszug.",
      fr: "Liqueur aux herbes. Ingrédients : macération d'herbes & épices.",
    },
    image: IMG["drinks-liquor"],
  },
  {
    id: slug("Baileys"),
    category: "drinks-liquor",
    name: "Baileys",
    i18nNames: { es: "Baileys", en: "Baileys", de: "Baileys", fr: "Baileys" },
    priceShot: 2.5, priceGlass: 4.0,
    descriptions: {
      es: "Crema irlandesa. Ingredientes: crema de leche, whisky, azúcar.",
      en: "Irish cream. Ingredients: dairy cream, whisky, sugar.",
      de: "Irischer Sahnelikör. Zutaten: Sahne, Whisky, Zucker.",
      fr: "Crème irlandaise. Ingrédients : crème laitière, whisky, sucre.",
    },
    image: IMG["drinks-liquor"],
  },

  /* ---------- DRINKS: Wines ---------- */
  {
    id: slug("Vino tinto cuarto"),
    category: "drinks-wine",
    name: "Vino tinto (1/4)",
    i18nNames: {
      es: "Vino tinto (1/4)",
      en: "Red wine (1/4)",
      de: "Rotwein (1/4)",
      fr: "Vin rouge (1/4)",
    },
    price: 3.50,
    descriptions: {
      es: "Vino de la casa. Ingredientes: uva tinta.",
      en: "House red. Ingredients: red grapes.",
      de: "Hauswein rot. Zutaten: rote Trauben.",
      fr: "Vin rouge maison. Ingrédients : raisins rouges.",
    },
    image: IMG["drinks-wine"],
  },
  {
    id: slug("Vino tinto medio"),
    category: "drinks-wine",
    name: "Vino tinto (media)",
    i18nNames: {
      es: "Vino tinto (media)",
      en: "Red wine (medium)",
      de: "Rotwein (mittel)",
      fr: "Vin rouge (moyen)",
    },
    price: 6.00,
    descriptions: {
      es: "Vino de la casa. Ingredientes: uva tinta.",
      en: "House red. Ingredients: red grapes.",
      de: "Hauswein rot. Zutaten: rote Trauben.",
      fr: "Vin rouge maison. Ingrédients : raisins rouges.",
    },
    image: IMG["drinks-wine"],
  },
  {
    id: slug("Vino blanco cuarto"),
    category: "drinks-wine",
    name: "Vino blanco (1/4)",
    i18nNames: {
      es: "Vino blanco (1/4)",
      en: "White wine (1/4)",
      de: "Weißwein (1/4)",
      fr: "Vin blanc (1/4)",
    },
    price: 3.50,
    descriptions: {
      es: "Vino de la casa. Ingredientes: uva blanca.",
      en: "House white. Ingredients: white grapes.",
      de: "Hauswein weiß. Zutaten: weiße Trauben.",
      fr: "Vin blanc maison. Ingrédients : raisins blancs.",
    },
    image: IMG["drinks-wine"],
  },
  {
    id: slug("Vino blanco medio"),
    category: "drinks-wine",
    name: "Vino blanco (media)",
    i18nNames: {
      es: "Vino blanco (media)",
      en: "White wine (medium)",
      de: "Weißwein (mittel)",
      fr: "Vin blanc (moyen)",
    },
    price: 6.00,
    descriptions: {
      es: "Vino de la casa. Ingredientes: uva blanca.",
      en: "House white. Ingredients: white grapes.",
      de: "Hauswein weiß. Zutaten: weiße Trauben.",
      fr: "Vin blanc maison. Ingrédients : raisins blancs.",
    },
    image: IMG["drinks-wine"],
  },
  {
    id: slug("Vino dulce cuarto"),
    category: "drinks-wine",
    name: "Vino dulce (1/4)",
    i18nNames: {
      es: "Vino dulce (1/4)",
      en: "Sweet wine (1/4)",
      de: "Süßwein (1/4)",
      fr: "Vin doux (1/4)",
    },
    price: 3.50,
    descriptions: {
      es: "Dulce de la casa. Ingredientes: uva, azúcar residual.",
      en: "House sweet. Ingredients: grapes, residual sugar.",
      de: "Haus-Süßwein. Zutaten: Trauben, Restsüße.",
      fr: "Vin doux maison. Ingrédients : raisins, sucre résiduel.",
    },
    image: IMG["drinks-wine"],
  },
  {
    id: slug("Vino dulce medio"),
    category: "drinks-wine",
    name: "Vino dulce (media)",
    i18nNames: {
      es: "Vino dulce (media)",
      en: "Sweet wine (medium)",
      de: "Süßwein (mittel)",
      fr: "Vin doux (moyen)",
    },
    price: 6.00,
    descriptions: {
      es: "Dulce de la casa. Ingredientes: uva, azúcar residual.",
      en: "House sweet. Ingredients: grapes, residual sugar.",
      de: "Haus-Süßwein. Zutaten: Trauben, Restsüße.",
      fr: "Vin doux maison. Ingrédients : raisins, sucre résiduel.",
    },
    image: IMG["drinks-wine"],
  },
];
